dev_directory: D:/dcase/dev_data_tmp
eval_directory: D:/dcase/eval_data
# dev_directory: /data/vizwave/dcase/dev_data
# eval_directory: /data/vizwave/dcase/eval_data
train_log_dir: ./train_log/lopez-2021-1
model_save_dir: ./model/lopez-2021-1
result_dir: ./result/lopez-2021-1
result_file: result.csv

max_fpr: 0.1
decision_threshold: 0.9
ext: wav

training:
  learning_rate: 0.001
  epochs : 2
  # batch_size : 512
  shuffle : True
  validation_split : 0.1
  weight_decay: 0.0
  lr_step_size: 50
  lr_gamma: 0.5
  verbose : 1

########### machine config ###########
ToyCar:
  batch_size: 128
  n_mels: 128
  n_frames: 1
  n_hop_frames: 1
  n_fft: 4096
  hop_length: 80
  power: 2.0

ToyTrain:
  n_mels: 128
  n_frames: 15
  n_hop_frames: 1
  n_fft: 1024
  hop_length: 512
  power: 2.0

fan:
  n_mels: 128
  n_frames: 15
  n_hop_frames: 1
  n_fft: 1024
  hop_length: 512
  power: 2.0

gearbox:
  n_mels: 128
  n_frames: 15
  n_hop_frames: 1
  n_fft: 1024
  hop_length: 512
  power: 2.0

pump:
  n_mels: 128
  n_frames: 15
  n_hop_frames: 1
  n_fft: 1024
  hop_length: 512
  power: 2.0

slider:
  n_mels: 128
  n_frames: 15
  n_hop_frames: 1
  n_fft: 1024
  hop_length: 512
  power: 2.0

valve:
  n_mels: 128
  n_frames: 15
  n_hop_frames: 1
  n_fft: 1024
  hop_length: 512
  power: 2.0