dev_directory: D:/dcase/dev_data_tmp
eval_directory: D:/dcase/eval_data
# dev_directory: /data/vizwave/dcase/dev_data
# eval_directory: /data/vizwave/dcase/eval_data
train_log_dir: ./train_log/ganomaly-1
model_save_dir: ./model/ganomaly-1
result_dir: ./result/ganomaly-1
result_file: result.csv

######### hyperparameters ##########
training:
  learning_rate: 0.001
  num_epochs : 2
  # batch_size : 512
  shuffle : True
  validation_split : 0.1
  weight_decay: 0.0
  lr_step_size: 50
  lr_gamma: 0.5
  verbose : 1

ext: wav

######### gamma distribution #########
max_fpr: 0.1
decision_threshold: 0.9  # q in gamma.ppf

########### machine config ###########
ToyCar:
  batch_size: 32
  input_samples: 16000
  n_mels: 128     
  # n_frames: 157      # n_frames = (sample_rate * t sec) / hop_length
  n_frames: 128      # n_frames = (sample_rate * t sec) / hop_length
  n_hop_frames: 1  
  n_fft: 1024
  # hop_length: 1024
  hop_length: 1250
  power: 2.0


slider:
  batch_size: 1
  input_samples: 16000
  n_mels: 128     
  n_frames: 157      # n_frames = (sample_rate * t sec) / hop_length
  n_hop_frames: 1  
  n_fft: 1024
  hop_length: 1024
  power: 2.0

pump:
  batch_size: 1
  input_samples: 16000
  n_mels: 128     
  n_frames: 157      # n_frames = (sample_rate * t sec) / hop_length
  n_hop_frames: 1  
  n_fft: 1024
  hop_length: 1024
  power: 2.0

# ToyTrain:
#   n_mels: 128
#   n_frames: 15
#   n_hop_frames: 1
#   n_fft: 1024
#   hop_length: 512
#   power: 2.0

# fan:
#   n_mels: 128
#   n_frames: 15
#   n_hop_frames: 1
#   n_fft: 1024
#   hop_length: 512
#   power: 2.0

# gearbox:
#   n_mels: 128
#   n_frames: 15
#   n_hop_frames: 1
#   n_fft: 1024
#   hop_length: 512
#   power: 2.0

# pump:
#   n_mels: 128
#   n_frames: 15
#   n_hop_frames: 1
#   n_fft: 1024
#   hop_length: 512
#   power: 2.0

# slider:
#   n_mels: 128
#   n_frames: 15
#   n_hop_frames: 1
#   n_fft: 1024
#   hop_length: 512
#   power: 2.0

# valve:
#   n_mels: 128
#   n_frames: 15
#   n_hop_frames: 1
#   n_fft: 1024
#   hop_length: 512
#   power: 2.0